services:
  wordpress:
    image: ubacode/ready_wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www/html
      - "./scripts/wordpress_secure_i nstallation.sh:/secure_install.sh:ro"
    networks:
      - wordpress
    depends_on:
      - db

  nginx:
    image: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html:ro
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - wordpress
    env_file: .env
    depends_on:
      - wordpress
    command: /bin/sh -c "envsubst '${WORDPRESS_URL}' < /etc/nginx/conf.d/nginx-conf && nginx -g 'daemon off;'"

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress

  phpMyAdmin:
    image: phpmyadmin
    restart: always
    env_file: .env
    networks:
      - wordpress
    ports:
      - 8080:80

  certbot:
    image: certbot/certbot
    restart: always
    env_file: .env
    networks:
      - wordpress
    volumes:
      - certbot:/var/www/certbot
      - certbot-conf:/etc/letsencrypt

volumes:
  wordpress:
  db:
  certbot:
  certbot-conf:

networks:
  wordpress:
